@startuml
hide footbox
agent "Content\nCreator" as IPSContentCreator
agent "Content\nConsumer" as IPSContentConsumer
cloud "Share Content" as cloud
Creator -> cloud : IPS
cloud -> Consumer : IPS
@enduml
