@startuml
skinparam svgDimensionStyle false
hide footbox

agent "On-Demand\nDocument\nSource" as ds
agent "HIE\nContent Creator" as hie
cloud "Document Sharing\n[PCC-1]" as cloud
agent "Content Consumer" as cc2

ds -> hie : Register On-Demand\nDocument Entry [ITI-61]
hie <-> cloud : IPS\nDocument
cloud <-> cc2 : IPS\nDocument


@enduml