@startuml
skinparam svgDimensionStyle false
hide footbox 

group Primary Data Holder
participant "Data Not\nAvailable to Portal" as nap 
participant "Available\nPatient Data" as apd 
participant "Provider Portal\nContent Creator" as ptp 




apd -> ptp : Conditions
apd -> ptp : Allergies
apd -> ptp : Medications
apd -> ptp : Immunizations
apd -> ptp : Care Plans
apd -> ptp : Alerts
apd -> ptp : Clinical Impressions

nap -->x ptp: Procedure Data
nap -->x ptp: Lab Data
nap -->x ptp: Device Data
end  

participant "Content\nConsumer" as cc2 
note over ptp, cc2: When the IPS is generated\nthe sections where the\nunavilable data would be\nare still generated with\nthe appropriate\nemptyReason codes 

ptp <-> cc2 : Document Sharing\n[PCC-1]

@enduml