@startuml
skinparam svgDimensionStyle false
hide footbox

group Primary Data Holder
participant "Available\nPatient Data" as apd 
participant "Patient Portal\nContent Creator" as pptp
 

apd -> pptp ++ : Conditions
apd -> pptp : Allergies
apd -> pptp : Medications
apd -> pptp : Immunizations
apd -> pptp : Care Plans
apd -> pptp : Alerts
apd -> pptp : Clinical Impressions
apd -> pptp : Procedure Data
apd -> pptp : Lab Data
apd -> pptp : Device Data

pptp -> pptp ++ : Adds Patient Story
pptp --> pptp : Masks Sensative Information
return saved 
end 

participant "Content Consumer" as cc2 
pptp <-> cc2 : Document Sharing\n[PCC-1]

@enduml