@startuml
skinparam svgDimensionStyle false
hide footbox

!pragma teoz true 
box "Health Data Source" #LightSkyBlue
participant "Primary Care Data Source\nContent Creator" as pcds

box "De-Identification" #SteelBlue
participant "Pseudonymization Service\nContent Consumer\nContent Creator" as pns

note over pcds, pns: Primary Data Source\nProvides a Fully Identifed\nPatient Summary Document 
pcds <-> pns: Document Sharing\n[PCC-1]
pns -> pns : Stage 1\nDe-Identification

participant "Anonymization Service\nContent Consumer\nContent Creator" as ans
note over pns, ans: Provides a Pseudonymized Data\nSet Formatted as an IPS Document\n(Stage 1 De-Identification)
pns <-> ans: Document Sharing\n[PCC-1]
ans -> ans : Stage 2\nDe-Identification
end box
end box 

box "Secondary Use" #MediumPurple
participant "Secondary Use Researcher\nContent Consumer" as sur 

note over ans, sur: Provides a\nFully De-Identified Data Set Formatted\nas an IPS Document\n(Stage 2 De-Identification)
ans <-> sur: Document Sharing\n[PCC-1]
end box

@enduml