@startuml
skinparam svgDimensionStyle false
hide footbox

agent "Content\nCreator" as IPSContentCreator
agent "Content\nConsumer" as IPSContentConsumer
cloud "Document\nSharing\n[PCC-1]" as cloud

IPSContentCreator <-> cloud : IPS
cloud <-> IPSContentConsumer : IPS
@enduml
