@startuml
skinparam svgDimensionStyle false
hide footbox
participant "IPS\nContent\nCreator" as IPSContentCreator
participant "IPS\nContent\nConsumer" as IPSContentConsumer
cloud "Share Content" as cloud
activate "IPS Content Consumer"
activate "IPS Content Creator"

IPSContentCreator -> cloud : Document Sharing [PCC-1]
cloud -> IPSContentConsumer : Document Sharing [PCC-1]

deactivate "IPS Content Creator"
deactivate "IPS Content Consumer"
@enduml
