Alias: $sct = http://snomed.info/sct
Alias: $ucum = http://unitsofmeasure.org
Alias: $loinc = http://loinc.org
Alias: $m49.htm = http://unstats.un.org/unsd/methods/m49/m49.htm
Alias: $StructureDefinition-Patient-uv-ips.html = https://hl7.org/fhir/uv/ips/StructureDefinition-Patient-uv-ips.html
Alias: $referencerange-meaning = http://hl7.org/fhir/ValueSet/referencerange-meaning
Alias: $2.16.840.1.113883.12.292 = https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.12.292
Alias: $observation-category = http://terminology.hl7.org/CodeSystem/observation-category
Alias: $ISCO08 = InternationalClassificationOfOccupations2008
Alias: $ISICRev4 = InternationalStandardIndustrialClassificationCodesRev4
Alias: $ONETSOC = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=3ED71C35-8147-492B-B88F-94953573E55F 
Alias: $SOC2010 = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=044B66C7-33CF-46D5-B252-BBA8A8819EEF
Alias: $PH_OccupationalDataForHealth_ODH = http://terminology.hl7.org/CodeSystem/PHOccupationalDataForHealthODH
Alias: $RxNorm = http://www.nlm.nih.gov/research/umls/rxnorm
Alias: $ICD10 = http://hl7.org/fhir/sid/icd-10
Alias: $ICD10-CM = http://hl7.org/fhir/sid/icd-10-cm