Alias: $sct = http://snomed.info/sct
Alias: $ucum = http://unitsofmeasure.org
Alias: $loinc = http://loinc.org
Alias: $m49.htm = http://unstats.un.org/unsd/methods/m49/m49.htm
Alias: $StructureDefinition-Patient-uv-ips.html = https://hl7.org/fhir/uv/ips/StructureDefinition-Patient-uv-ips.html
Alias: $referencerange-meaning = http://hl7.org/fhir/ValueSet/referencerange-meaning
Alias: $2.16.840.1.113883.12.292 = https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.12.292
Alias: $observation-category = http://terminology.hl7.org/CodeSystem/observation-category
Alias: $ISCO08 = https://profiles.ihe.net/PCC/ODH/CodeSystem/ISCO08
Alias: $ISICRev4 = https://profiles.ihe.net/PCC/ODH/CodeSystem/ISICRev4
Alias: $ONETSOC = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=3ED71C35-8147-492B-B88F-94953573E55F 
Alias: $SOC2010 = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=044B66C7-33CF-46D5-B252-BBA8A8819EEF
Alias: $PH_OccupationalDataForHealth_ODH = http://terminology.hl7.org/CodeSystem/PHOccupationalDataForHealthODH
Alias: $RxNorm = http://www.nlm.nih.gov/research/umls/rxnorm
Alias: $ICD10 = http://hl7.org/fhir/sid/icd-10
Alias: $ICD10-CM = http://hl7.org/fhir/sid/icd-10-cm
Alias: $v3-WorkClassificationODH = http://terminology.hl7.org/CodeSystem/v3-WorkClassificationODH
Alias: $PHOccupationalDataForHealthODH = http://terminology.hl7.org/CodeSystem/PHOccupationalDataForHealthODH
Alias: $v3-ObservationValue = http://terminology.hl7.org/CodeSystem/v3-ObservationValue
Alias: $v2-0203 = http://terminology.hl7.org/CodeSystem/v2-0203

// Aliases for example files
Alias: $v3-ActClass = http://terminology.hl7.org/CodeSystem/v3-ActClass
Alias: $condition-clinical = http://terminology.hl7.org/CodeSystem/condition-clinical
Alias: $condition-ver-status = http://terminology.hl7.org/CodeSystem/condition-ver-status
Alias: $condition-category = http://terminology.hl7.org/CodeSystem/condition-category
Alias: $allergyintolerance-clinical = http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical
Alias: $allergyintolerance-verification = http://terminology.hl7.org/CodeSystem/allergyintolerance-verification
Alias: $v3-ObservationInterpretation = http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation
Alias: $v3-ActSite = http://terminology.hl7.org/CodeSystem/v3-ActSite
Alias: $v3-RouteOfAdministration = http://terminology.hl7.org/CodeSystem/v3-RouteOfAdministration
Alias: $v2-0443 = http://terminology.hl7.org/CodeSystem/v2-0443
Alias: $observation-category = http://terminology.hl7.org/CodeSystem/observation-category